apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-front
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort : 32000
  selector:
    app: flask-front
